const menu = [
  {
    id: 1,
    title: "Black Bodycon Dress",
    category: "dress",
    price: 15.99,
    img: "./images/1.jpg",
  },
  {
    id: 2,
    title: "Red Sundress",
    category: "dress",
    price: 13.99,
    img: "./images/2.jpg",
  },
  {
    id: 3,
    title: "Floral dress",
    category: "dress",
    price: 6.99,
    img: "./images/3.jpg",
  },
  {
    id: 4,
    title: "Smile shirt",
    category: "shirt",
    price: 20.99,
    img: "./images/4.jpg",
  },
  {
    id: 5,
    title: "White comfy shirt",
    category: "shirt",
    price: 22.99,
    img: "./images/5.jpg",
  },
  {
    id: 6,
    title: "Fancy Top",
    category: "shirt",
    price: 18.99,
    img: "./images/6.jpg",
  },
  {
    id: 7,
    title: "Wide legged jeans",
    category: "jeans",
    price: 8.99,
    img: "./images/7.jpg",
  },
  {
    id: 8,
    title: "Skinny jeans",
    category: "jeans",
    price: 12.99,
    img: "./images/8.jpg",
  },
  {
    id: 9,
    title: "Shredded jeans",
    category: "jeans",
    price: 16.99,
    img: "./images/9.jpg",
  },
  {
    id: 10,
    title: "Diamond heels",
    category: "heels",
    price: 16.99,
    img: "./images/10.jpg",
  },
  {
    id: 11,
    title: "Feathered heels",
    category: "heels",
    price: 16.99,
    img: "./images/11.jpg",
  },
  {
    id: 12,
    title: "Leathered heels",
    category: "heels",
    price: 16.99,
    img: "./images/12.jpg",
  },
];
export default menu;
